package br.ufg.inf.mestrado.hermeswidget.ontologies;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.ontology.*;
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from m3.2.owl 
 * @author Auto-generated by schemagen on 19 mai 2017 08:41 
 */
public class M3 {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/iot/vocab/m3-lite#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "1.1";
    
    /** <p>The observations made by the sensors are affected by the direction of the 
     *  sensing device. This property allows observations of the sensor to be associated 
     *  to the Direction concept.</p>
     */
    public static final ObjectProperty hasDirection = m_model.createObjectProperty( "http://purl.org/iot/vocab/m3-lite#hasDirection" );
    
    /** <p>This property is used to classify devices by DomainOfInterest (e.g., blood 
     *  pressure sensor is used in healthcare).</p>
     */
    public static final ObjectProperty hasDomainOfInterest = m_model.createObjectProperty( "http://purl.org/iot/vocab/m3-lite#hasDomainOfInterest" );
    
    /** <p>Each sensing device can have a different sensing mechanism which may result 
     *  in different kinds of sensor data. This property links observation of the 
     *  sensor to the associated MeasurementType.</p>
     */
    public static final ObjectProperty hasMeasurementType = m_model.createObjectProperty( "http://purl.org/iot/vocab/m3-lite#hasMeasurementType" );
    
    /** <p>This property links sound to its environmental source.</p> */
    public static final ObjectProperty hasSoundSource = m_model.createObjectProperty( "http://purl.org/iot/vocab/m3-lite#hasSoundSource" );
    
    /** <p>This property links sensed phenomena to its environmental source.</p> */
    public static final ObjectProperty hasSource = m_model.createObjectProperty( "http://purl.org/iot/vocab/m3-lite#hasSource" );
    
    /** <p>The ABS (Anti-lock Braking System) receives information from ABS computer 
     *  to control the pressure on the breaks, This helps the wheels not to get locked 
     *  up, it adjust the break pressure and prevents the wheels from locking. (Definition 
     *  Source Google).</p>
     */
    public static final OntClass ABS = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ABS" );
    
    /** <p>Initial E-UTRAN Radio Access Bearer establishment success rate.</p> */
    public static final OntClass AccInitialERabEstabSuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AccInitialERabEstabSuccRate" );
    
    /** <p>Initial E-UTRAN Radio Access Bearer setup success rate.</p> */
    public static final OntClass AccInitialERabSetupSuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AccInitialERabSetupSuccRate" );
    
    /** <p>Radio Resource Control connection setup success rate.</p> */
    public static final OntClass AccRrcConnSetupSuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AccRrcConnSetupSuccRate" );
    
    /** <p>S1 (S1 standardized interface between eNB and Evolved Packet Core) signalling 
     *  establishment success rate.</p>
     */
    public static final OntClass AccS1SigEstabSuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AccS1SigEstabSuccRate" );
    
    /** <p>The rate of change of the velocity of a particle with respect to time.</p> */
    public static final OntClass Acceleration = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Acceleration" );
    
    /** <p>The acceleration at a given instant of time.</p> */
    public static final OntClass AccelerationInstantaneous = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AccelerationInstantaneous" );
    
    /** <p>Accelerometers are used to automatically determine the orientation in which 
     *  the user is holding the IoT Object (portrait or landscape).</p>
     */
    public static final OntClass Accelerometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Accelerometer" );
    
    /** <p>The product of the voltage across a branch of an alternating-current circuit 
     *  and the component of the electric current that is in phase with the voltage.</p>
     */
    public static final OntClass ActivePower = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ActivePower" );
    
    /** <p>Agriculture, Smart farm as an Internet of Things (IoT) applicative domain.</p> */
    public static final OntClass Agriculture = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Agriculture" );
    
    /** <p>An actuator to automatically switch on/off the air conditioner.</p> */
    public static final OntClass AirConditioner = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirConditioner" );
    
    /** <p>Sensor used to measure air humidity.</p> */
    public static final OntClass AirHumiditySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirHumiditySensor" );
    
    /** <p>Air Pollutant Sensor are devices that detect and monitor the presence of air 
     *  pollution in the surrounding area (source Wikipedia).</p>
     */
    public static final OntClass AirPollutantSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirPollutantSensor" );
    
    /** <p>Usually measured using Air Quality Index (AQI), it is the measure of Air Pollution 
     *  in the environment. It is similar to Air Quality.</p>
     */
    public static final OntClass AirPollution = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirPollution" );
    
    /** <p>Usually measured using an air quality index (AQI) that is a number used by 
     *  government agencies to communicate to the public how polluted the air currently 
     *  is or how polluted it is forecast to become. Different countries have their 
     *  own air quality indices, corresponding to different national air quality standards. 
     *  It is the measure of Air Quality of the environment. It is similar to Air 
     *  Pollution. (Source Wikipedia).</p>
     */
    public static final OntClass AirQuality = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirQuality" );
    
    /** <p>The temperature of the air that would be indicated by a thermometer exposed 
     *  to the air at a location sheltered from direct solar radiation.</p>
     */
    public static final OntClass AirTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirTemperature" );
    
    /** <p>Device to measure the Air temperature of either indoor or outdoor atmosphere.</p> */
    public static final OntClass AirThermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AirThermometer" );
    
    /** <p>An actuator to automatically switch on/off the alarm system.</p> */
    public static final OntClass AlarmSystem = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AlarmSystem" );
    
    /** <p>Measure of Alcohol Level in the system.</p> */
    public static final OntClass AlcoholLevel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AlcoholLevel" );
    
    /** <p>Device used to detect and measure Alcohol Level in the system.</p> */
    public static final OntClass AlcoholLevelSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AlcoholLevelSensor" );
    
    /** <p>The ampere is the SI unit for measuring an electric current which is the flow 
     *  of electric charges through a surface at the rate of one coulomb per second.The 
     *  ampere is the SI unit for measuring an electric current which is the flow 
     *  of electric charges through a surface at the rate of one coulomb per second.</p>
     */
    public static final OntClass Ampere = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Ampere" );
    
    /** <p>It is the rate of change of angular displacement and is a vector quantity 
     *  (more precisely, a pseudovector) that specifies the angular speed (rotational 
     *  speed) of an object and the axis about which the object is rotating. (Source 
     *  Wikipedia).</p>
     */
    public static final OntClass AngularSpeed = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AngularSpeed" );
    
    /** <p>when the source of the sound were animals.</p> */
    public static final OntClass Animals = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Animals" );
    
    /** <p>The pressure exerted by the atmosphere as a consequence of gravitational attraction 
     *  exerted upon the column of air lying directly above the point in question.</p>
     */
    public static final OntClass AtmosphericPressure = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AtmosphericPressure" );
    
    /** <p>Atmospheric Pressure Sensor, Barometer or Barometric Pressure Sensor is a 
     *  scientific instrument used in meteorology to measure atmospheric pressure.</p>
     */
    public static final OntClass AtmosphericPressureSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AtmosphericPressureSensor" );
    
    /** <p>When the devices are set to take the observations Automatically without any 
     *  external aid.</p>
     */
    public static final OntClass AutomaticSensing = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#AutomaticSensing" );
    
    /** <p>Metric unit of atmospheric pressure equal to 14.50 pounds per square inch 
     *  (lb/in2), 1.02 kilograms per square centimetre (kg/cm2), 29.53 inches of mercury 
     *  (in Hg), or 0.9869 atmosphere.</p>
     */
    public static final OntClass Bar = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Bar" );
    
    /** <p>A tagging device can be Barcode.</p> */
    public static final OntClass Barcode = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Barcode" );
    
    /** <p>Measure of the percentage of the battery capacity that remains available.</p> */
    public static final OntClass BatteryLevel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BatteryLevel" );
    
    /** <p>Beat Per Minute (bpm) is the unit to measure heart rate.</p> */
    public static final OntClass BeatPerMinute = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BeatPerMinute" );
    
    /** <p>An actuator to automatically switch on/off the window blinds.</p> */
    public static final OntClass Blind = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Blind" );
    
    /** <p>Measure of Blood glucose level or blood sugar level.</p> */
    public static final OntClass BloodGlucose = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BloodGlucose" );
    
    /** <p>Measure of the pressure in your blood vessels when your heart rests between 
     *  beats.</p>
     */
    public static final OntClass BloodPressure = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BloodPressure" );
    
    /** <p>Device used to measure Blood Pressure.</p> */
    public static final OntClass BloodPressureSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BloodPressureSensor" );
    
    /** <p>Measure of board temperature.</p> */
    public static final OntClass BoardTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BoardTemperature" );
    
    /** <p>Device used to measure board temperature.</p> */
    public static final OntClass BoardThermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BoardThermometer" );
    
    /** <p>Measure of body temperature.</p> */
    public static final OntClass BodyTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BodyTemperature" );
    
    /** <p>Device used to measure body temperature.</p> */
    public static final OntClass BodyThermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BodyThermometer" );
    
    /** <p>An actuator to automatically switch on/off the boiler.</p> */
    public static final OntClass Boiler = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Boiler" );
    
    /** <p>Smart Home/Building Automation as an Internet of Things (IoT) applicative 
     *  domain.</p>
     */
    public static final OntClass BuildingAutomation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BuildingAutomation" );
    
    /** <p>Measure of building or room temperature.</p> */
    public static final OntClass BuildingTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#BuildingTemperature" );
    
    /** <p>Carbon Dioxide (CO2) measure in the atmosphere.</p> */
    public static final OntClass CO2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CO2" );
    
    /** <p>Carbon Dioxide (CO2) Sensor used to measure level of CO2 in the atmosphere.</p> */
    public static final OntClass CO2Sensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CO2Sensor" );
    
    /** <p>Device to detect Carbon Monoxide (CO) in the environment.</p> */
    public static final OntClass COSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#COSensor" );
    
    /** <p>Measure of blood calcium level.</p> */
    public static final OntClass Calcium = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Calcium" );
    
    /** <p>If the measurement was taken when the sensor was being calibrated.</p> */
    public static final OntClass CalibrationSensing = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CalibrationSensing" );
    
    /** <p>Candela is the luminous intensity, in a given direction, of a source that 
     *  emits monochromatic radiation of frequency 540 x 10^12 hertz and that has 
     *  a radiant intensity in that direction of 1/683 watt per steradian. (Source 
     *  Wikipedia).</p>
     */
    public static final OntClass Candela = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Candela" );
    
    /** <p>Measure of the ability of a system to store an electric charge.</p> */
    public static final OntClass Capacitance = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Capacitance" );
    
    /** <p>The centibar is a unit of pressure defined as 1e-2 bar.</p> */
    public static final OntClass Centibar = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Centibar" );
    
    /** <p>A metric unit of length, equal to one hundredth of a metre.</p> */
    public static final OntClass Centimetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Centimetre" );
    
    /** <p>Measure of Chemical Agent Atmospheric Concentration</p> */
    public static final OntClass ChemicalAgentAtmosphericConcentration = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentAtmosphericConcentration" );
    
    /** <p>Measure of the concentration of chemical particles suspended in the atmosphere.</p> */
    public static final OntClass ChemicalAgentAtmosphericConcentrationAirParticles = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentAtmosphericConcentrationAirParticles" );
    
    /** <p>Measure of the concentration of Carbon Monoxide (CO) gas suspended in the 
     *  atmosphere.</p>
     */
    public static final OntClass ChemicalAgentAtmosphericConcentrationCO = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentAtmosphericConcentrationCO" );
    
    /** <p>Measure of the concentration of dust suspended in the air.</p> */
    public static final OntClass ChemicalAgentAtmosphericConcentrationDust = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentAtmosphericConcentrationDust" );
    
    /** <p>Measure of the concentration of NO2 gas suspended in the atmosphere.</p> */
    public static final OntClass ChemicalAgentAtmosphericConcentrationNO2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentAtmosphericConcentrationNO2" );
    
    /** <p>The concentration of ozone (O3) gas suspended in the atmosphere.</p> */
    public static final OntClass ChemicalAgentAtmosphericConcentrationO3 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentAtmosphericConcentrationO3" );
    
    /** <p>Measure of Chemical Agent Concentration</p> */
    public static final OntClass ChemicalAgentConcentration = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentConcentration" );
    
    /** <p>Measure of Chemical Agent Concentration in Water</p> */
    public static final OntClass ChemicalAgentWaterConcentration = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentWaterConcentration" );
    
    /** <p>Measure of NH4 ion concentration in Water</p> */
    public static final OntClass ChemicalAgentWaterConcentrationNH4Ion = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentWaterConcentrationNH4Ion" );
    
    /** <p>Measure of NO3 ion concentration in Water</p> */
    public static final OntClass ChemicalAgentWaterConcentrationNO3Ion = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentWaterConcentrationNO3Ion" );
    
    /** <p>Measure of O2 concentration in Water</p> */
    public static final OntClass ChemicalAgentWaterConcentrationO2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ChemicalAgentWaterConcentrationO2" );
    
    /** <p>Measure of the cholesterol level in a system.</p> */
    public static final OntClass Cholesterol = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Cholesterol" );
    
    /** <p>Device used to measure the cholesterol level in a system.</p> */
    public static final OntClass CholesterolSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CholesterolSensor" );
    
    /** <p>Smart City as an Internet of Things (IoT) applicative domain.</p> */
    public static final OntClass City = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#City" );
    
    /** <p>sensor that measures time</p> */
    public static final OntClass Clock = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Clock" );
    
    /** <p>Measure of cloud cover at a certain time.</p> */
    public static final OntClass CloudCover = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CloudCover" );
    
    /** <p>Cloud Cover Sensor is used to detect whether it is sunny, cloudy, etc.</p> */
    public static final OntClass CloudCoverSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CloudCoverSensor" );
    
    /** <p>An actuator to automatically switch on/off the coffee machine.</p> */
    public static final OntClass CoffeeMachine = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CoffeeMachine" );
    
    /** <p>Communication related properties.</p> */
    public static final OntClass Communication = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Communication" );
    
    /** <p>Actuating devices for Computer or PC.</p> */
    public static final OntClass Computer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Computer" );
    
    /** <p>Measure of ability to conduct electricity. It is measured in siemens per metre 
     *  (S/m).</p>
     */
    public static final OntClass Conductivity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Conductivity" );
    
    /** <p>Device used to measure the conductivity of a system.</p> */
    public static final OntClass ConductivitySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ConductivitySensor" );
    
    /** <p>When the source of the sound was a construction work.</p> */
    public static final OntClass ConstructionWork = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ConstructionWork" );
    
    /** <p>Triples for location in the (Latitude, Longitude, Altitude) format.</p> */
    public static final OntClass Coordinates = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Coordinates" );
    
    /** <p>SI unit of electric charge.</p> */
    public static final OntClass Coulomb = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Coulomb" );
    
    /** <p>Number of available particular things.</p> */
    public static final OntClass Count = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Count" );
    
    /** <p>Number of available bicycles at a particular bicycle docking station.</p> */
    public static final OntClass CountAvailableBicycles = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CountAvailableBicycles" );
    
    /** <p>Number of taxis available at a particular taxi stop.</p> */
    public static final OntClass CountAvailableTaxis = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CountAvailableTaxis" );
    
    /** <p>Number of empty docking points at a particular bicycle docking station.</p> */
    public static final OntClass CountEmptyDockingPoints = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#CountEmptyDockingPoints" );
    
    /** <p>Sensors that reckons occurrences or repetitions of physical objects, phenomena 
     *  or events.</p>
     */
    public static final OntClass Counter = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Counter" );
    
    /** <p>When the source of the sound was crowd.</p> */
    public static final OntClass Crowd = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Crowd" );
    
    /** <p>An actuator to automatically open/close the cupboard.</p> */
    public static final OntClass Cupboard = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Cupboard" );
    
    /** <p>An actuator to automatically open/close the curtain.</p> */
    public static final OntClass Curtain = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Curtain" );
    
    /** <p>Day is a unit of time.</p> */
    public static final OntClass Day = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Day" );
    
    /** <p>Decibel is a logarithmic unit used to express the ratio of two values of a 
     *  physical quantity. It is often used to measure sound level.</p>
     */
    public static final OntClass Decibel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Decibel" );
    
    /** <p>Sound pressure sensed by the human ear.</p> */
    public static final OntClass DecibelA = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DecibelA" );
    
    /** <p>Degree.</p> */
    public static final OntClass Degree = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Degree" );
    
    /** <p>A plane angle unit which is equal to 1/360 of a full rotation or pi/180 rad.</p> */
    public static final OntClass DegreeAngle = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DegreeAngle" );
    
    /** <p>A temperature unit which is equal to one kelvin degree. However, they have 
     *  their zeros at different points. The centigrade scale has its zero at 273.15 
     *  K.</p>
     */
    public static final OntClass DegreeCelsius = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DegreeCelsius" );
    
    /** <p>Measurement Unit to represent temperature on the Fahrenheit scale.</p> */
    public static final OntClass DegreeFahrenheit = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DegreeFahrenheit" );
    
    /** <p>Difference between Dewpoint and surface temperatures.</p> */
    public static final OntClass DeltaDewPoint = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DeltaDewPoint" );
    
    /** <p>Device that measures the difference between Dewpoint and surface temperatures.</p> */
    public static final OntClass DeltaDewPointSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DeltaDewPointSensor" );
    
    /** <p>It is the temperature to which air must be cooled at constant pressure to 
     *  condense to form liquid.</p>
     */
    public static final OntClass DewPoint = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DewPoint" );
    
    /** <p>Device that measures dew point.</p> */
    public static final OntClass DewPointSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DewPointSensor" );
    
    /** <p>The temperature at which dew forms and is a measure of atmospheric moisture. 
     *  It is the temperature to which air must be cooled at constant pressure and 
     *  water content to reach saturation. A higher dew point indicates more moisture 
     *  in the air; a dew point greater than 20 Degree C (68 Degree F) is considered 
     *  uncomfortable and greater than 22 Degree C (72 Degree F) is considered to 
     *  be extremely humid.</p>
     */
    public static final OntClass DewPointTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DewPointTemperature" );
    
    /** <p>Measure of the pressure in the arteries when the heart rests between beats.</p> */
    public static final OntClass DiastolicBloodPressure = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DiastolicBloodPressure" );
    
    /** <p>Without dimensions; having no appreciable or noteworthy extent. Without physical 
     *  meaning.</p>
     */
    public static final OntClass Dimensionless = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Dimensionless" );
    
    /** <p>Measurements of sensors are affected by the direction of the sensing device. 
     *  This concept is used to reflect it.</p>
     */
    public static final OntClass Direction = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Direction" );
    
    /** <p>The geodetic azimuth of the direction towards which an object is point to.</p> */
    public static final OntClass DirectionAzimuth = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DirectionAzimuth" );
    
    /** <p>The course or direction in which a object (vehicle, person, ...) is moving.</p> */
    public static final OntClass DirectionHeading = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DirectionHeading" );
    
    /** <p>An actuator to automatically switch on/off the dishwasher.</p> */
    public static final OntClass DishWasher = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DishWasher" );
    
    /** <p>Measure of how far apart objects are.</p> */
    public static final OntClass Distance = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Distance" );
    
    /** <p>Distance Sensor is used to detect distance between two objects for example: 
     *  the safety distance with other cars. Distance sensor can be a laser.</p>
     */
    public static final OntClass DistanceSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DistanceSensor" );
    
    /** <p>Application Domain for example: health, environment, etc.</p> */
    public static final OntClass DomainOfInterest = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DomainOfInterest" );
    
    /** <p>An actuator to automatically open/close the door.</p> */
    public static final OntClass Door = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Door" );
    
    /** <p>This sensor detects if a door is in the state of OPEN or CLOSED.</p> */
    public static final OntClass DoorStateSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DoorStateSensor" );
    
    /** <p>Describes if a door is OPEN or CLOSED.</p> */
    public static final OntClass DoorStatus = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DoorStatus" );
    
    /** <p>An actuator to automatically open/close the drawer.</p> */
    public static final OntClass Drawer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Drawer" );
    
    /** <p>A sensing device that measures dust particle concentration.</p> */
    public static final OntClass DustSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#DustSensor" );
    
    /** <p>Unit to measure Air Quality in European cities.</p> */
    public static final OntClass EAQI = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#EAQI" );
    
    /** <p>ECG or EKG (Electrocardiogram) device.</p> */
    public static final OntClass ECG = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ECG" );
    
    /** <p>The actuator for turning ESP on/off.</p> */
    public static final OntClass ESP = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ESP" );
    
    /** <p>It is the physical property of matter that causes it to experience a force 
     *  when placed in an electromagnetic field. (Source Wikipedia).</p>
     */
    public static final OntClass ElectricCharge = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricCharge" );
    
    /** <p>Electric current is the flow of electric charge. It is a base quantity in 
     *  the International System of Units. Electric current is electric charge divided 
     *  by time. Electric Current is the flow (movement) of electric charge. The amount 
     *  of electric current through some surface, e.g., a section through a copper 
     *  conductor, is defined as the amount of electric charge flowing through that 
     *  surface over time.</p>
     */
    public static final OntClass ElectricCurrent = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricCurrent" );
    
    /** <p>Electric field is the electric force per unit charge.</p> */
    public static final OntClass ElectricField = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricField" );
    
    /** <p>A field of force associated with a moving electric charge equivalent to an 
     *  electric field and a magnetic field at right angles to each other and to the 
     *  direction of propagation. Applied to the 1800 MHz UHF band.</p>
     */
    public static final OntClass ElectricField1800MHz = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricField1800MHz" );
    
    /** <p>A field of force associated with a moving electric charge equivalent to an 
     *  electric field and a magnetic field at right angles to each other and to the 
     *  direction of propagation. Applied to the 2100 MHz UHF band.</p>
     */
    public static final OntClass ElectricField2100MHz = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricField2100MHz" );
    
    /** <p>A field of force associated with a moving electric charge equivalent to an 
     *  electric field and a magnetic field at right angles to each other and to the 
     *  direction of propagation. Applied to the 2400 MHz UHF band.</p>
     */
    public static final OntClass ElectricField2400MHz = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricField2400MHz" );
    
    /** <p>A field of force associated with a moving electric charge equivalent to an 
     *  electric field and a magnetic field at right angles to each other and to the 
     *  direction of propagation. Applied to the 900 MHz UHF band.</p>
     */
    public static final OntClass ElectricField900Mhz = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricField900Mhz" );
    
    /** <p>Scientific instrument for measuring electromagnetic fields (EMF). Most of 
     *  them measure the electromagnetic radiation flux density (DC fields) or the 
     *  change in an electromagnetic field over time (AC fields).</p>
     */
    public static final OntClass ElectricFieldSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricFieldSensor" );
    
    /** <p>Electric potential is the potential energy per unit charge associated with 
     *  static (time-invariant) electric field.</p>
     */
    public static final OntClass ElectricPotential = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricPotential" );
    
    /** <p>The electrical resistance of an electrical conductor is the opposition to 
     *  the passage of an electric current through that conductor.</p>
     */
    public static final OntClass ElectricalResistance = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricalResistance" );
    
    /** <p>Sensor that measures the changes in electrical or magnetic signals based on 
     *  an environmental input.</p>
     */
    public static final OntClass ElectricalSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ElectricalSensor" );
    
    /** <p>Affective Science, Emotion, Mood, Emotional State, Brain Wave as an Internet 
     *  of Things (IoT) applicative domain.</p>
     */
    public static final OntClass Emotion = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Emotion" );
    
    /** <p>Energy is the property that must be transferred to an object in order to perform 
     *  work on. (Source Wikipedia).</p>
     */
    public static final OntClass Energy = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Energy" );
    
    /** <p>Energy or Smart Grid as an Internet of Things (IoT) applicative domain.</p> */
    public static final OntClass EnergyDOI = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#EnergyDOI" );
    
    /** <p>Sensor to measure power or energy consumption.</p> */
    public static final OntClass EnergyMeter = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#EnergyMeter" );
    
    /** <p>Environment (earthquake, flooding, fire, pollution) as an Internet of Things 
     *  (IoT) applicative domain.</p>
     */
    public static final OntClass Environment = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Environment" );
    
    /** <p>Experiment based measurements.</p> */
    public static final OntClass Experiment = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Experiment" );
    
    /** <p>Device to detect is a person has fallen.</p> */
    public static final OntClass FallDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FallDetector" );
    
    /** <p>When the source of the sound was Fan.</p> */
    public static final OntClass Fan = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Fan" );
    
    /** <p>SI unit of electrical capacitance.</p> */
    public static final OntClass Farad = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Farad" );
    
    /** <p>Property used to determine the level a certain object such as waste bin is 
     *  filled upto.</p>
     */
    public static final OntClass FillLevel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FillLevel" );
    
    /** <p>Ratio of volume of combustible exhaust fluid to the total volume of diesel 
     *  exhaust fluid storage container.</p>
     */
    public static final OntClass FillLevelGasTank = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FillLevelGasTank" );
    
    /** <p>Ratio of volume of combustible exhaust fluid to the total volume of diesel 
     *  exhaust fluid storage container. This is the value for the primary tank of 
     *  the vehicle.</p>
     */
    public static final OntClass FillLevelGasTank1 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FillLevelGasTank1" );
    
    /** <p>Ratio of volume of combustible exhaust fluid to the total volume of diesel 
     *  exhaust fluid storage container. This is the value for the secondary tank 
     *  of the vehicle.</p>
     */
    public static final OntClass FillLevelGasTank2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FillLevelGasTank2" );
    
    /** <p>Ratio between the current filleage level and the total capacity of a waste 
     *  container.</p>
     */
    public static final OntClass FillLevelWasteContainer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FillLevelWasteContainer" );
    
    /** <p>The actuator for turning on or off the fog lamp.</p> */
    public static final OntClass FogLamp = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FogLamp" );
    
    /** <p>Measure of temperature of the food.</p> */
    public static final OntClass FoodTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FoodTemperature" );
    
    /** <p>An actuator to automatically open/close the freezer.</p> */
    public static final OntClass Freezer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Freezer" );
    
    /** <p>Frequency is the number of occurrences of a repeating event per unit time.</p> */
    public static final OntClass Frequency = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Frequency" );
    
    /** <p>Device used to detect the frequency.</p> */
    public static final OntClass FrequencySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FrequencySensor" );
    
    /** <p>An actuator to automatically switch on/off the fridge.</p> */
    public static final OntClass Fridge = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Fridge" );
    
    /** <p>The amount of fuel a vehicle uses to travel a particular distance at a particular 
     *  speed.</p>
     */
    public static final OntClass FuelConsumption = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FuelConsumption" );
    
    /** <p>A measure that displays the instantaneous fuel consumption of a vehicle during 
     *  its operation.</p>
     */
    public static final OntClass FuelConsumptionInstantaneous = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FuelConsumptionInstantaneous" );
    
    /** <p>Accumulated amount of fuel used during vehicle operation.</p> */
    public static final OntClass FuelConsumptionTotal = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FuelConsumptionTotal" );
    
    /** <p>Device used to detect fuel level in a system such a car.</p> */
    public static final OntClass FuelLevel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#FuelLevel" );
    
    /** <p>Device that allows an object to localize itself.</p> */
    public static final OntClass GPSSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GPSSensor" );
    
    /** <p>Device that detects the presence of gases in an area, often as part of a safety 
     *  system.</p>
     */
    public static final OntClass GasDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GasDetector" );
    
    /** <p>Device used to detect poisonous gaseous in the environment.</p> */
    public static final OntClass GaseousPollutantSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GaseousPollutantSensor" );
    
    /** <p>Gauss is the CGS unit of measurement of magnetic flux density (or magnetic 
     *  induction) (B) (Source Wikipedia)</p>
     */
    public static final OntClass Gauss = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Gauss" );
    
    /** <p>Device used to detect glucometer, blood sugar, blood glucose level.</p> */
    public static final OntClass Glucometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Glucometer" );
    
    /** <p>It is a metric system unit of mass</p> */
    public static final OntClass Gram = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Gram" );
    
    /** <p>It is defined by mass in grams divided by volume in cubic metres.</p> */
    public static final OntClass GramPerCubicMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GramPerCubicMetre" );
    
    /** <p>It shows how many grams of a certain substance are present in one litre of 
     *  a usually liquid or gaseous mixture.</p>
     */
    public static final OntClass GramPerLitre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GramPerLitre" );
    
    /** <p>A gyrometer is an instrument which measures an angular speed.</p> */
    public static final OntClass GyrometerSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GyrometerSensor" );
    
    /** <p>A gyroscope is a device for measuring or maintaining orientation.</p> */
    public static final OntClass GyroscopeSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#GyroscopeSensor" );
    
    /** <p>Device used to measure of hydrogen sulphide in the environment.</p> */
    public static final OntClass H2SSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#H2SSensor" );
    
    /** <p>Healthcare as an Internet of Things (IoT) applicative domain.</p> */
    public static final OntClass Health = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Health" );
    
    /** <p>The number of times your heart beats each minute (bpm).</p> */
    public static final OntClass HeartBeat = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#HeartBeat" );
    
    /** <p>Device to count heart beats per minute.</p> */
    public static final OntClass HeartBeatSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#HeartBeatSensor" );
    
    /** <p>An actuator to automatically switch on/off the heating.</p> */
    public static final OntClass Heating = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Heating" );
    
    /** <p>The SI unit of frequency, equal to one cycle per second.</p> */
    public static final OntClass Hertz = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Hertz" );
    
    /** <p>Hour of the day.</p> */
    public static final OntClass Hour = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Hour" );
    
    /** <p>Measure of Household Appliance Temperature.</p> */
    public static final OntClass HouseholdApplianceTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#HouseholdApplianceTemperature" );
    
    /** <p>Device used to detect if an object (vehicle, room, place, etc.) is occupied 
     *  by Human.</p>
     */
    public static final OntClass HumanPresenceDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#HumanPresenceDetector" );
    
    /** <p>A quantity representing the amount of water vapour in the atmosphere or in 
     *  a gas.</p>
     */
    public static final OntClass Humidity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Humidity" );
    
    /** <p>Humidity sensor or hygrometer is an instrument used for measuring the moisture 
     *  concent in the environment.</p>
     */
    public static final OntClass HumiditySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#HumiditySensor" );
    
    /** <p>A hydrophone is a microphone designed to be used underwater for recording 
     *  or listening to underwater sound.</p>
     */
    public static final OntClass Hydrophone = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Hydrophone" );
    
    /** <p>Illuminance is the total luminous flux incident on a surface, per unit area.</p> */
    public static final OntClass Illuminance = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Illuminance" );
    
    /** <p>Sensor that detects and conveys the information that constitutes an image.</p> */
    public static final OntClass ImageSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ImageSensor" );
    
    /** <p>Length in inches.</p> */
    public static final OntClass Inch = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Inch" );
    
    /** <p>Arbitrary indirect reference which should be translated into meaningful measurements 
     *  by using the corresponding decoding algorithm detailed in the resource description. 
     *  In this case the returned values can only take certain values from a finite 
     *  set.</p>
     */
    public static final OntClass Index = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Index" );
    
    /** <p>Downlink Latency.</p> */
    public static final OntClass IntDlLatency = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#IntDlLatency" );
    
    /** <p>Downlink Throughput.</p> */
    public static final OntClass IntDlThroughputKbps = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#IntDlThroughputKbps" );
    
    /** <p>Uplink Packet Loss.</p> */
    public static final OntClass IntUlPacketLoss = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#IntUlPacketLoss" );
    
    /** <p>Uplink Throughput.</p> */
    public static final OntClass IntUlThroughputKbps = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#IntUlThroughputKbps" );
    
    /** <p>If the measurement was tagged invalid.</p> */
    public static final OntClass Invalid = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Invalid" );
    
    /** <p>Ionising radiation is radiation that carries enough energy to free electrons 
     *  from atoms or molecules, thereby ionizing them. Gamma rays, X-rays, and the 
     *  higher ultraviolet part of the electromagnetic spectrum are ionizing, whereas 
     *  the lower ultraviolet part of the electromagnetic spectrum, and also the lower 
     *  part of the spectrum below UV, including visible light (including nearly all 
     *  types of laser light), infrared, microwaves, and radio waves are all considered 
     *  non-ionizing radiation.</p>
     */
    public static final OntClass IonisingRadiation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#IonisingRadiation" );
    
    /** <p>An actuator to automatically irrigate.</p> */
    public static final OntClass Irrigation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Irrigation" );
    
    /** <p>Each of the accountable elements within a group.</p> */
    public static final OntClass Item = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Item" );
    
    /** <p>Kelvin is a unit of measurement for temperature.</p> */
    public static final OntClass Kelvin = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Kelvin" );
    
    /** <p>Measure of electrical energy equivalent to a power consumption of one thousand 
     *  watts for one hour.</p>
     */
    public static final OntClass KiloWattHour = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#KiloWattHour" );
    
    /** <p>It is a unit of data transfer rate equal to: 1,000 bits per second.</p> */
    public static final OntClass KilobitsPerSecond = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#KilobitsPerSecond" );
    
    /** <p>The SI unit of mass, it is equal to the mass of the international prototype 
     *  of the kilogram.</p>
     */
    public static final OntClass Kilogram = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Kilogram" );
    
    /** <p>It is SI derived unit of density, defined by mass in kilograms divided by 
     *  volume in cubic metres.</p>
     */
    public static final OntClass KilogramPerCubicMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#KilogramPerCubicMetre" );
    
    /** <p>A metric unit of measurement equal to 1,000 metres (approx 0.62 miles).</p> */
    public static final OntClass Kilometre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Kilometre" );
    
    /** <p>It is a unit of speed, expressing the number of kilometres travelled in one 
     *  hour.</p>
     */
    public static final OntClass KilometrePerHour = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#KilometrePerHour" );
    
    /** <p>An actuator to automatically switch on/off the lamp.</p> */
    public static final OntClass Lamp = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Lamp" );
    
    /** <p>An actuator to automatically switch on/off the lavatory.</p> */
    public static final OntClass Lavatory = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Lavatory" );
    
    /** <p>Leaf wetness is a meteorological parameter that describes the amount of dew 
     *  and precipitation left on surfaces. It is used for monitoring leaf moisture 
     *  for agricultural purposes, such as fungus and disease control, for control 
     *  of irrigation systems, and for detection of fog and dew conditions, and early 
     *  detection of rainfall. (Source Wikipedia).</p>
     */
    public static final OntClass LeafWetness = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LeafWetness" );
    
    /** <p>Leaf Wetness Sensor is used in agriculture to check whether the plants need 
     *  to be watered.</p>
     */
    public static final OntClass LeafWetnessSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LeafWetnessSensor" );
    
    /** <p>Light/Illuminance Sensor is used to adjust the brightness of the surface.</p> */
    public static final OntClass LightSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LightSensor" );
    
    /** <p>A metric unit of capacity defined as the volume of one kilogram of water under 
     *  standard conditions. It is equal to 1,000 cubic centimetres.</p>
     */
    public static final OntClass Litre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Litre" );
    
    /** <p>A consumption unit which is equal to the one of a vehicle which needs 1 fuel 
     *  litre in order to traverse 100 kilometres.</p>
     */
    public static final OntClass LitrePer100Kilometres = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LitrePer100Kilometres" );
    
    /** <p>Measure the average power consumption of the LoRa interface nodes.</p> */
    public static final OntClass LoRaInterfaceEnergyMeter = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LoRaInterfaceEnergyMeter" );
    
    /** <p>A particular place or position.</p> */
    public static final OntClass LocationQK = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LocationQK" );
    
    /** <p>The SI unit of luminous flux, equal to the amount of light emitted per second 
     *  in a unit solid angle of one steradian from a uniform source of one candela.</p>
     */
    public static final OntClass Lumen = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Lumen" );
    
    /** <p>Luminous Flux is the measure of the perceived power of light.</p> */
    public static final OntClass LuminousFlux = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LuminousFlux" );
    
    /** <p>It is a measure of the wavelength-weighted power emitted by a light source 
     *  in a particular direction per unit solid angle, based on the luminosity function, 
     *  a standardized model of the sensitivity of the human eye. The SI unit of luminous 
     *  intensity is the candela (cd), an SI base unit. (Source Wikipedia)</p>
     */
    public static final OntClass LuminousIntensity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#LuminousIntensity" );
    
    /** <p>The SI unit of illuminance, equal to one lumen per square metre.</p> */
    public static final OntClass Lux = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Lux" );
    
    /** <p>A region around a magnetic material or a moving electric charge within which 
     *  the force of magnetism acts.</p>
     */
    public static final OntClass MagneticField = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MagneticField" );
    
    /** <p>It is the magnetic flux through a surface is the surface integral of the normal 
     *  component of the magnetic field (B) passing through that surface. The SI unit 
     *  of magnetic flux is the weber (Wb). (Source Wikipedia).</p>
     */
    public static final OntClass MagneticFluxDensity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MagneticFluxDensity" );
    
    /** <p>A magnetometer is an device that measures magnetism�either magnetization of 
     *  magnetic material like a ferromagnet, or the strength and, in some cases, 
     *  direction of the magnetic field at a point in space. (Source Wikipedia).</p>
     */
    public static final OntClass Magnetometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Magnetometer" );
    
    /** <p>If the measurement was taken when human effort was involved.</p> */
    public static final OntClass Manual = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Manual" );
    
    /** <p>Mass is a property of a physical body. It is the measure of an object's resistance 
     *  to acceleration when a net force is applied.</p>
     */
    public static final OntClass Mass = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Mass" );
    
    /** <p>Type of Measurement done using a device.</p> */
    public static final OntClass MeasurementType = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MeasurementType" );
    
    /** <p>Device used to detect Methane in the environment.</p> */
    public static final OntClass MethaneSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MethaneSensor" );
    
    /** <p>It is the unit of length.</p> */
    public static final OntClass Metre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Metre" );
    
    /** <p>A speed/velocity unit which is equal to the speed of an object traveling 1 
     *  metre distance in one second.</p>
     */
    public static final OntClass MetrePerSecond = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MetrePerSecond" );
    
    /** <p>It is the unit of acceleration.</p> */
    public static final OntClass MetrePerSecondSquare = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MetrePerSecondSquare" );
    
    /** <p>It is a unit of electric current, or amount of electric charge per second.</p> */
    public static final OntClass Microampere = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Microampere" );
    
    /** <p>It is a unit of mass equal to one billionth (1�10^?9) of a kilogram.</p> */
    public static final OntClass Microgram = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Microgram" );
    
    /** <p>Microgram per cubic metre is a unit of density defined as microgram divided 
     *  by cubic metre. Milligram per cubic metre is a derived unit in the International 
     *  System of Units.</p>
     */
    public static final OntClass MicrogramPerCubicMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MicrogramPerCubicMetre" );
    
    /** <p>It is a unit of electromotive force or potential difference equal to one millionth 
     *  of a volt.</p>
     */
    public static final OntClass Microvolt = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Microvolt" );
    
    /** <p>It is a unit of power.</p> */
    public static final OntClass Microwatt = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Microwatt" );
    
    /** <p>It is one of the unit for radiative and other energy fluxes.</p> */
    public static final OntClass MicrowattPerSquareCentimetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MicrowattPerSquareCentimetre" );
    
    /** <p>An actuator to automatically switch on/off the Microwave.</p> */
    public static final OntClass Microwave = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Microwave" );
    
    /** <p>Measure of the number of miles or the average distance that a vehicle can 
     *  travel on a specified quantity of fuel</p>
     */
    public static final OntClass Mileage = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Mileage" );
    
    /** <p>The distance which can be travelled by the vehicle before the next service 
     *  inspection is required. A negative distance is transmitted if the service 
     *  inspection has been passed.</p>
     */
    public static final OntClass MileageDistanceToService = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MileageDistanceToService" );
    
    /** <p>The total distance travelled by the particular vehicle since its initial production.</p> */
    public static final OntClass MileageTotal = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MileageTotal" );
    
    /** <p>It is a unit of length that is equal to 1,760 yards (approx. 1.609 kilometres).</p> */
    public static final OntClass Miles = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Miles" );
    
    /** <p>One thousandth of an ampere.</p> */
    public static final OntClass Milliampere = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Milliampere" );
    
    /** <p>One thousandth of a bar.</p> */
    public static final OntClass Millibar = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Millibar" );
    
    /** <p>One thousandth of a gram.</p> */
    public static final OntClass Milligram = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Milligram" );
    
    /** <p>It is a density measurement unit.</p> */
    public static final OntClass MilligramPerCubicMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MilligramPerCubicMetre" );
    
    /** <p>Level of Dissolved substance in liquid measured in mg per litre.</p> */
    public static final OntClass MilligramPerLitre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MilligramPerLitre" );
    
    /** <p>A dose unit which is equal to 1 milligram of a substance per square metre 
     *  of surface area of the recipient subject.</p>
     */
    public static final OntClass MilligramPerSquareMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MilligramPerSquareMetre" );
    
    /** <p>One thousandth of a litre (0.002 pint).</p> */
    public static final OntClass Millilitre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Millilitre" );
    
    /** <p>One thousandth of a metre (0.039 in).</p> */
    public static final OntClass Millimetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Millimetre" );
    
    /** <p>A unit of both speed (scalar) and velocity (vector), defined as the distance 
     *  of one millimetre travelled per unit hour.</p>
     */
    public static final OntClass MillimetrePerHour = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MillimetrePerHour" );
    
    /** <p>One thousandth of a second.</p> */
    public static final OntClass Millisecond = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Millisecond" );
    
    /** <p>One thousandth of a volt.</p> */
    public static final OntClass Millivolt = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Millivolt" );
    
    /** <p>It is a measure of the intensity of the signal of a radio transmitter.</p> */
    public static final OntClass MillivoltPerMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MillivoltPerMetre" );
    
    /** <p>A unit of power equal to one thousandth of a watt.</p> */
    public static final OntClass Milliwatt = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Milliwatt" );
    
    /** <p>A Minute of Angle (MOA) is an angular measurement. A MOA is 1/60th of a degree.</p> */
    public static final OntClass MinuteAngle = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MinuteAngle" );
    
    /** <p>A unit of time equal to 60 seconds or 1/60th of an hour.</p> */
    public static final OntClass MinuteTime = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MinuteTime" );
    
    /** <p>A millimetre of mercury is a manometric unit of pressure, formerly defined 
     *  as the extra pressure generated by a column of mercury one millimetre high 
     *  and now defined as precisely 133.322387415 pascals. It is denoted by the symbol 
     *  mmHg. It is used to measure blood pressure measurements (systolic and diastolic).</p>
     */
    public static final OntClass MmHg = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MmHg" );
    
    /** <p>It is the amount of a substance that corresponds to its formula mass in milligrams. 
     *  MmolPerLitre is used to measure cholesterol.</p>
     */
    public static final OntClass MmolPerLitre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MmolPerLitre" );
    
    /** <p>Handover Execution.</p> */
    public static final OntClass MobHoExecSuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MobHoExecSuccRate" );
    
    /** <p>Handover Preparation Success Rate.</p> */
    public static final OntClass MobHoPrepSuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MobHoPrepSuccRate" );
    
    /** <p>Handover Mobility Success Rate.</p> */
    public static final OntClass MobMobilitySuccRate = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MobMobilitySuccRate" );
    
    /** <p>It is the action or process of moving or being moved.</p> */
    public static final OntClass Motion = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Motion" );
    
    /** <p>Indicator of whether a person (or object) is detected upon his/her/its movement.</p> */
    public static final OntClass MotionState = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MotionState" );
    
    /** <p>Indicates whether motion of the vehicle is detected or not.</p> */
    public static final OntClass MotionStateVehicle = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#MotionStateVehicle" );
    
    /** <p>A tagging device can be NFC (Near Field Communication).</p> */
    public static final OntClass NFC = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#NFC" );
    
    /** <p>Device used to detect NH3 level in the environment.</p> */
    public static final OntClass NH3Sensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#NH3Sensor" );
    
    /** <p>Sensor detecting levels of Nitrogen Dioxide (NO2) in the environment.</p> */
    public static final OntClass NO2Sensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#NO2Sensor" );
    
    /** <p>Device used to detect Nitrogen Oxide (NO) in the environment.</p> */
    public static final OntClass NOSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#NOSensor" );
    
    /** <p>When the source of the sound were noisy neighbours.</p> */
    public static final OntClass Neighbours = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Neighbours" );
    
    /** <p>Device used to detect Ozone (O3) in the environment.</p> */
    public static final OntClass O3Sensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#O3Sensor" );
    
    /** <p>An odometer or odograph is an instrument that indicates distance travelled 
     *  by a vehicle, such as bicycle or automobile.</p>
     */
    public static final OntClass Odometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Odometer" );
    
    /** <p>Ohm is the unit of electrical resistance.</p> */
    public static final OntClass Ohm = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Ohm" );
    
    /** <p>Okta is the unit to measure the cloud cover.</p> */
    public static final OntClass Okta = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Okta" );
    
    /** <p>A sensing device that measures dust particle concentration using optical sensing 
     *  mean.</p>
     */
    public static final OntClass OpticalDustSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#OpticalDustSensor" );
    
    /** <p>Relates to phenomenon and unit that are not available currently in the current 
     *  version of Taxonomy.</p>
     */
    public static final OntClass Others = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Others" );
    
    /** <p>Device used to detect Oxygen (O2) in the environment.</p> */
    public static final OntClass OxygenSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#OxygenSensor" );
    
    /** <p>It is a numeric scale used to specify the acidity or basicity of an aqueous 
     *  solution.</p>
     */
    public static final OntClass PH = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PH" );
    
    /** <p>Device used to detect PH level.</p> */
    public static final OntClass PHSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PHSensor" );
    
    /** <p>It describes the concentration of something in water or soil.</p> */
    public static final OntClass PPM = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PPM" );
    
    /** <p>Unit for pressure (e.g., atmospheric pressure).</p> */
    public static final OntClass Pascal = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Pascal" );
    
    /** <p>Pedometer is used to count the number of steps when walking, running, etc.</p> */
    public static final OntClass Pedometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Pedometer" );
    
    /** <p>It is the amount in or for every hundred.</p> */
    public static final OntClass Percent = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Percent" );
    
    /** <p>Location, Place, GPS coordinates as an Internet of Things (IoT) applicative 
     *  domain.</p>
     */
    public static final OntClass Place = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Place" );
    
    /** <p>It is the measure of Blood Potassium Level.</p> */
    public static final OntClass Potassium = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Potassium" );
    
    /** <p>A unit of weight equal to 16 oz. 1 pound= 453.592 grams</p> */
    public static final OntClass Pound = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Pound" );
    
    /** <p>It is the rate, per unit time, at which electrical energy is transferred by 
     *  an electric circuit.</p>
     */
    public static final OntClass Power = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Power" );
    
    /** <p>It is any product of the condensation of atmospheric water vapour that falls 
     *  under gravity.</p>
     */
    public static final OntClass Precipitation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Precipitation" );
    
    /** <p>It is a device measuring the amount of precipitation.</p> */
    public static final OntClass PrecipitationSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PrecipitationSensor" );
    
    /** <p>Measure to know if an object is present. It is usually boolean.</p> */
    public static final OntClass Presence = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Presence" );
    
    /** <p>Device used to detect if on object is occupied or not.</p> */
    public static final OntClass PresenceDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceDetector" );
    
    /** <p>Indicates the presence of the first driver card.</p> */
    public static final OntClass PresenceStateDriverCard = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceStateDriverCard" );
    
    /** <p>Indicates the presence of the first driver card.</p> */
    public static final OntClass PresenceStateDriverCard1 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceStateDriverCard1" );
    
    /** <p>Indicates the presence of the second driver card.</p> */
    public static final OntClass PresenceStateDriverCard2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceStateDriverCard2" );
    
    /** <p>The presence or absence of an emergency vehicle (ambulance, fire fighters, 
     *  etc.).</p>
     */
    public static final OntClass PresenceStateEmergencyVehicle = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceStateEmergencyVehicle" );
    
    /** <p>The presence or absence of a vehicle parked.</p> */
    public static final OntClass PresenceStateParking = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceStateParking" );
    
    /** <p>The presence or absence of people passing.</p> */
    public static final OntClass PresenceStatePeople = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PresenceStatePeople" );
    
    /** <p>It is the physical force exerted on or against an object by something in contact 
     *  with it.</p>
     */
    public static final OntClass Pressure = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Pressure" );
    
    /** <p>A device used to detect pressure. For example, it can be attached on the bed 
     *  to infer if the user is lying, sleeping, sitting, bed occupancy, etc.</p>
     */
    public static final OntClass PressureSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PressureSensor" );
    
    /** <p>Measure to detect proximity.</p> */
    public static final OntClass Proximity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Proximity" );
    
    /** <p>Detect if something is within proximity of a sensor.</p> */
    public static final OntClass ProximitySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ProximitySensor" );
    
    /** <p>When the source of the sound was public transit.</p> */
    public static final OntClass PublicTransit = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PublicTransit" );
    
    /** <p>Pulse Oxymeter, SpO2, Blood Oxygen Saturation Sensor are used to measure the 
     *  concentration of oxygen in the blood.</p>
     */
    public static final OntClass PulseOxymeter = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#PulseOxymeter" );
    
    /** <p>A tagging device can be QRCode.</p> */
    public static final OntClass QRCode = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#QRCode" );
    
    /** <p>A tagging device can be RFID.</p> */
    public static final OntClass RFID = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RFID" );
    
    /** <p>The radian is a unit of angular measure defined such that an angle of one 
     *  radian subtended from the centre of a unit circle produces an arc with arc 
     *  length 1.</p>
     */
    public static final OntClass Radian = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Radian" );
    
    /** <p>The radian per second is defined as the change in the orientation of an object, 
     *  in radians, every second. The radian per second is the SI unit of angular 
     *  (rotational) speed.</p>
     */
    public static final OntClass RadianPerSecond = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RadianPerSecond" );
    
    /** <p>A particle detector, also known as a radiation detector or Geiger counter, 
     *  is a device used to detect, track, and/or identify ionising particles, such 
     *  as those produced by nuclear decay, cosmic radiation, or reactions in a particle 
     *  accelerator.</p>
     */
    public static final OntClass RadiationParticleDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RadiationParticleDetector" );
    
    /** <p>The number of ionizing events detected in one minute.</p> */
    public static final OntClass RadiationParticlesPerMinute = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RadiationParticlesPerMinute" );
    
    /** <p>The depth of precipitation (water-equivalent) that accumulated over a measurement 
     *  time quantity.</p>
     */
    public static final OntClass Rainfall = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Rainfall" );
    
    /** <p>The portion of electricity that establishes and sustains the electric and 
     *  magnetic fields of alternating-current equipment.</p>
     */
    public static final OntClass ReactivePower = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ReactivePower" );
    
    /** <p>Activity Recognized. This is usually made available as a part of analysis 
     *  done by Google. The available activities recognized are IN_VEHICLE, ON_BICYCLE, 
     *  ON_FOOT, RUNNING, STILL, TILTING, UNKNOWN, and WALKING.</p>
     */
    public static final OntClass RecognizedActivity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RecognizedActivity" );
    
    /** <p>The ratio of vapour pressure to saturation vapour pressure, where vapour pressure 
     *  is the pressure exerted by the molecules of water vapour and saturation vapour 
     *  pressure is the pressure exerted by molecules of water vapour in AIR that 
     *  has attained saturation.</p>
     */
    public static final OntClass RelativeHumidity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RelativeHumidity" );
    
    /** <p>Connected Users to a communication channel/platform</p> */
    public static final OntClass ResAverageLicConnectedUsers = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ResAverageLicConnectedUsers" );
    
    /** <p>ERAB Drop.</p> */
    public static final OntClass RetERabDrop = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RetERabDrop" );
    
    /** <p>Revolutions per minute (abbreviated rpm, RPM, rev/min, r/min) is a measure 
     *  of the frequency of rotation, specifically the number of rotations around 
     *  a fixed axis in one minute. It is used as a measure of rotational speed of 
     *  a mechanical component.</p>
     */
    public static final OntClass RevolutionsPerMinute = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RevolutionsPerMinute" );
    
    /** <p>Ratio of time on which a road lane section is occupied by vehicles within 
     *  a given period of time.</p>
     */
    public static final OntClass RoadOccupancy = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RoadOccupancy" );
    
    /** <p>Device used to measure the road Surface temperature.</p> */
    public static final OntClass RoadSurfaceThermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RoadSurfaceThermometer" );
    
    /** <p>Temperature of the road.</p> */
    public static final OntClass RoadTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RoadTemperature" );
    
    /** <p>Temperature of a room.</p> */
    public static final OntClass RoomTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RoomTemperature" );
    
    /** <p>Rotational speed (or speed of revolution) of an object rotating around an 
     *  axis is the number of turns of the object divided by time, specified as revolutions 
     *  per minute (rpm), revolutions per second (rev/s), or radians per second (rad/s). 
     *  (Source Wikipedia)</p>
     */
    public static final OntClass RotationalSpeed = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RotationalSpeed" );
    
    /** <p>Rotational speed is a property that is the rate of rotation of a material 
     *  around an axis, in this case the engine cylinders.</p>
     */
    public static final OntClass RotationalSpeedEngine = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#RotationalSpeedEngine" );
    
    /** <p>Device use to detect Sulphur Dioxide (SO2) level in the environment.</p> */
    public static final OntClass SO2Sensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SO2Sensor" );
    
    /** <p>It is a measure of the amount of oxygenated haemoglobin in the blood.</p> */
    public static final OntClass SPO2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SPO2" );
    
    /** <p>It is the measure of all the salts dissolved in water.</p> */
    public static final OntClass Salinity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Salinity" );
    
    /** <p>Device use to detect salinity of water.</p> */
    public static final OntClass SaltMeter = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SaltMeter" );
    
    /** <p>Arbitrary indirect reference which should be translated into meaningful measurements 
     *  by using the corresponding decoding algorithm detailed in the resource description. 
     *  In this case the returned values are part of a continuous variable which can 
     *  take any numeric value.</p>
     */
    public static final OntClass Scale = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Scale" );
    
    /** <p>Actuator used to turn Seat Belt Tension Actuator on or off.</p> */
    public static final OntClass SeatBeltTensionSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SeatBeltTensionSensor" );
    
    /** <p>It is a unit of angular measurement equal to 1/60 of one degree.</p> */
    public static final OntClass SecondAngle = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SecondAngle" );
    
    /** <p>Qualitatively defined as the second division of the hour by sixty, the first 
     *  division by sixty being the minute. SI definition of second is "the duration 
     *  of 9 192 631 770 periods of the radiation corresponding to the transition 
     *  between the two hyperfine levels of the ground state of the cesium 133 atom.</p>
     */
    public static final OntClass SecondTime = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SecondTime" );
    
    /** <p>Seismometers are instruments that measure motions of the ground, including 
     *  those of seismic waves generated by earthquakes, volcanic eruptions, and other 
     *  seismic sources.</p>
     */
    public static final OntClass Seismometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Seismometer" );
    
    /** <p>Shake sensor is used to deduce the quality of the road, earthquakes.</p> */
    public static final OntClass ShakeSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ShakeSensor" );
    
    /** <p>An actuator to automatically switch on/off the shower.</p> */
    public static final OntClass Shower = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Shower" );
    
    /** <p>Conductivity is measured in Siemens per metre (S/m).</p> */
    public static final OntClass SiemensPerMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SiemensPerMetre" );
    
    /** <p>An actuator to automatically switch on/off the sink.</p> */
    public static final OntClass Sink = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Sink" );
    
    /** <p>When source of the sound were sirens either from ambulance, police car or 
     *  factory etc.</p>
     */
    public static final OntClass Sirens = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Sirens" );
    
    /** <p>Electroderal activity (also known as skin conductance or galvanic skin response) 
     *  directly correlates to the sympathetic nervous system activity and thus provides 
     *  a powerful tool for monitoring arousal and certain aspects of autonomic regulation.</p>
     */
    public static final OntClass SkinConductance = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SkinConductance" );
    
    /** <p>Device used to detect Skin Conductance.</p> */
    public static final OntClass SkinConductanceSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SkinConductanceSensor" );
    
    /** <p>Device used to detect if there is a fire or the smoke.</p> */
    public static final OntClass SmokeDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SmokeDetector" );
    
    /** <p>The actuator that turn Snow chains on/off.</p> */
    public static final OntClass SnowChains = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SnowChains" );
    
    /** <p>Measure of Blood Sodium level.</p> */
    public static final OntClass Sodium = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Sodium" );
    
    /** <p>It is the quantity of water contained in a material, such as soil.</p> */
    public static final OntClass SoilHumidity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoilHumidity" );
    
    /** <p>Soil Humidity sensor, Soil moisture, Hygrometer are an instrument used for 
     *  measuring the soil moisture or soil humidity.</p>
     */
    public static final OntClass SoilHumiditySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoilHumiditySensor" );
    
    /** <p>The force per unit area required to remove film water from soil.</p> */
    public static final OntClass SoilMoistureTension = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoilMoistureTension" );
    
    /** <p>Soil temperature is the bulk temperature of the soil, not the surface (skin) 
     *  temperature.</p>
     */
    public static final OntClass SoilTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoilTemperature" );
    
    /** <p>This sensor reports Soil temperature.</p> */
    public static final OntClass SoilThermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoilThermometer" );
    
    /** <p>It is the power per unit area received from the Sun in the form of electromagnetic 
     *  radiation in the wavelength range of the measuring instrument. (Source Wikipedia).</p>
     */
    public static final OntClass SolarRadiation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SolarRadiation" );
    
    /** <p>Device used to detect Solar Radiation.</p> */
    public static final OntClass SolarRadiationSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SolarRadiationSensor" );
    
    /** <p>Measure of noise level in the environment</p> */
    public static final OntClass Sound = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Sound" );
    
    /** <p>Sound pressure level is a logarithmic measure of the RMS sound pressure of 
     *  a sound relative to a reference value, the threshold of hearing. The reference 
     *  sound pressure was chosen conventionally to correspond to the quietest sound 
     *  at 1000 Hz that the human ear can detect (20 uPa). In this case, the specific 
     *  parameter is measured in an open environment.</p>
     */
    public static final OntClass SoundPressureLevel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoundPressureLevel" );
    
    /** <p>Similar to Sound.</p> */
    public static final OntClass SoundPressureLevelAmbient = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoundPressureLevelAmbient" );
    
    /** <p>Sensor used to detect Noise level. It can be Sound Sensor, Noise level Sensor, 
     *  Volume sensor, Microphone</p>
     */
    public static final OntClass SoundSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoundSensor" );
    
    /** <p>Source where the sound originated.</p> */
    public static final OntClass SoundSource = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SoundSource" );
    
    /** <p>Environmental Origin of a particular observation. With respect to one kind 
     *  of Source (Sound source), it can be coming from traffic, siren of a police 
     *  car, etc.</p>
     */
    public static final OntClass Source = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Source" );
    
    /** <p>The rate at which someone or something moves or operates or is able to move 
     *  or operate.</p>
     */
    public static final OntClass Speed = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Speed" );
    
    /** <p>A measure of the average rate of motion of an object.</p> */
    public static final OntClass SpeedAverage = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SpeedAverage" );
    
    /** <p>A measure of the instantaneous rate of motion of an object.</p> */
    public static final OntClass SpeedInstantaneous = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SpeedInstantaneous" );
    
    /** <p>A measure of the median rate of motion of an object.</p> */
    public static final OntClass SpeedMedian = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SpeedMedian" );
    
    /** <p>Sensor used to detect speed.</p> */
    public static final OntClass SpeedSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SpeedSensor" );
    
    /** <p>It is a measure of number of Step taken.</p> */
    public static final OntClass Step = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Step" );
    
    /** <p>The position of the Sun in the sky is a function of both time and the geographic 
     *  coordinates of the observer on the surface of the Earth. (Source Wikipedia).</p>
     */
    public static final OntClass SunPositionDirection = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SunPositionDirection" );
    
    /** <p>Sensor used to detect sun position.</p> */
    public static final OntClass SunPositionDirectionSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SunPositionDirectionSensor" );
    
    /** <p>It is the altitude of the sun, the angle between the horizon and the centre 
     *  of the sun's disc.</p>
     */
    public static final OntClass SunPositionElevation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SunPositionElevation" );
    
    /** <p>Device used to detect sun elevation.</p> */
    public static final OntClass SunPositionElevationSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SunPositionElevationSensor" );
    
    /** <p>It is the pressure when the heart beats while pumping blood.</p> */
    public static final OntClass SystolicBloodPressure = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#SystolicBloodPressure" );
    
    /** <p>An actuator to automatically switch on/off the television.</p> */
    public static final OntClass TV = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TV" );
    
    /** <p>An actuator to automatically switch on/off the Telephone.</p> */
    public static final OntClass Telephone = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Telephone" );
    
    /** <p>It is the air temperature.</p> */
    public static final OntClass Temperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Temperature" );
    
    /** <p>The temperature of a vehicle engine.</p> */
    public static final OntClass TemperatureEngine = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TemperatureEngine" );
    
    /** <p>The temperature of the air that would be indicated by a thermometer exposed 
     *  to the air inside a waste container.</p>
     */
    public static final OntClass TemperatureWasteContainer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TemperatureWasteContainer" );
    
    /** <p>It is the SI unit of magnetic flux density.</p> */
    public static final OntClass Tesla = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Tesla" );
    
    /** <p>A device to measure the temperature in a room or outside.</p> */
    public static final OntClass Thermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Thermometer" );
    
    /** <p>It is a device used to monitor the throttle position of a vehicle.</p> */
    public static final OntClass ThrottleSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#ThrottleSensor" );
    
    /** <p>Indicator of whether a person (or object) has overpassed a particular time 
     *  threshold (e.g. maximum number of hours driving, etc.)</p>
     */
    public static final OntClass TimeRelatedState = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TimeRelatedState" );
    
    /** <p>Indicator of whether the driver of a vehicle approaches or exceeds his/her 
     *  working time limits.</p>
     */
    public static final OntClass TimeRelatedStateDriver = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TimeRelatedStateDriver" );
    
    /** <p>Indicates if the first driver approaches or exceeds working time limits (or 
     *  other limits).</p>
     */
    public static final OntClass TimeRelatedStateDriver1 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TimeRelatedStateDriver1" );
    
    /** <p>Indicates if the second driver approaches or exceeds working time limits (or 
     *  other limits).</p>
     */
    public static final OntClass TimeRelatedStateDriver2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TimeRelatedStateDriver2" );
    
    /** <p>Sequence of characters or encoded information identifying when a certain event 
     *  occurred, usually giving date and time of day, sometimes accurate to a small 
     *  fraction of a second. This representation should be encoded following ISO8601.</p>
     */
    public static final OntClass Timestamp = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Timestamp" );
    
    /** <p>It is a non-SI metric unit of mass equal to 1,000 kilograms.</p> */
    public static final OntClass Tonne = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Tonne" );
    
    /** <p>Device that captures and records physical touch or embrace on a device and/or 
     *  object.</p>
     */
    public static final OntClass TouchSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TouchSensor" );
    
    /** <p>Tourism as an Internet of Things (IoT) applicative domain.</p> */
    public static final OntClass Tourism = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Tourism" );
    
    /** <p>When the source of the sound was traffic.</p> */
    public static final OntClass Traffic = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Traffic" );
    
    /** <p>The intensity of a traffic flow is the number of vehicles passing a cross 
     *  section of a road in a unit of time.</p>
     */
    public static final OntClass TrafficIntensity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#TrafficIntensity" );
    
    /** <p>Transportation, Smart Car/Vehicle, Intelligent Transport System (ITS) as an 
     *  Internet of Things (IoT) applicative domain.</p>
     */
    public static final OntClass Transportation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Transportation" );
    
    /** <p>Ultrasonic sensors are used to deduce human posture in smart home for example.</p> */
    public static final OntClass UltrasonicSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#UltrasonicSensor" );
    
    /** <p>Device used to count the number of vehicles (e.g., used within the Citypulse 
     *  project).</p>
     */
    public static final OntClass VehicleCountSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VehicleCountSensor" );
    
    /** <p>Measure to indicates whether the vehicle is exceeding the legal speed limit.</p> */
    public static final OntClass VehicleOverspeedState = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VehicleOverspeedState" );
    
    /** <p>Device used to detect if an vehicle is present at a place.</p> */
    public static final OntClass VehiclePresenceDetector = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VehiclePresenceDetector" );
    
    /** <p>Number of vehicles that traverse a concrete region of the space in one minute.</p> */
    public static final OntClass VehiclesPerMinute = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VehiclesPerMinute" );
    
    /** <p>An actuator to automatically open/close the ventilation.</p> */
    public static final OntClass Ventilation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Ventilation" );
    
    /** <p>The state of being able to see or be seen.</p> */
    public static final OntClass Visibility = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Visibility" );
    
    /** <p>Device used to detect Visibility.</p> */
    public static final OntClass VisibilitySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VisibilitySensor" );
    
    /** <p>The SI unit of electromotive force, the difference of potential that would 
     *  carry one ampere of current against one ohm resistance.</p>
     */
    public static final OntClass Volt = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Volt" );
    
    /** <p>In electric power transmission and distribution, volt-ampere reactive (var) 
     *  is a unit in which reactive power is expressed in an AC electric power system.</p>
     */
    public static final OntClass VoltAmpereReactive = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VoltAmpereReactive" );
    
    /** <p>An electromotive force or potential difference expressed in volts (Source 
     *  Google).</p>
     */
    public static final OntClass Voltage = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Voltage" );
    
    /** <p>Device which can measure the difference in electric potential energy between 
     *  two points per unit electric charge.</p>
     */
    public static final OntClass VoltageSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#VoltageSensor" );
    
    /** <p>An actuator to automatically switch on/off the washing machine.</p> */
    public static final OntClass WashingMachine = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WashingMachine" );
    
    /** <p>Device used to measure the conductivity of water.</p> */
    public static final OntClass WaterConductivitySensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterConductivitySensor" );
    
    /** <p>The height reached by the water in a reservoir, river, storage tank, or similar.</p> */
    public static final OntClass WaterLevel = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterLevel" );
    
    /** <p>Sensor used to measure NH4 concentration level in the water.</p> */
    public static final OntClass WaterNH4IonSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterNH4IonSensor" );
    
    /** <p>Sensor used to measure NO3 concentration level in the water.</p> */
    public static final OntClass WaterNO3IonSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterNO3IonSensor" );
    
    /** <p>Sensor used to measure O2 concentration level in the water.</p> */
    public static final OntClass WaterO2IonSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterO2IonSensor" );
    
    /** <p>Device used to detect PH level of water.</p> */
    public static final OntClass WaterPHSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterPHSensor" );
    
    /** <p>Sea surface temperature (SST) is the water temperature close to the ocean's 
     *  surface.</p>
     */
    public static final OntClass WaterTemperature = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterTemperature" );
    
    /** <p>This sensor reports Water temperature.</p> */
    public static final OntClass WaterThermometer = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WaterThermometer" );
    
    /** <p>It is the SI unit of power, equivalent to one joule per second, corresponding 
     *  to the rate of consumption of energy in an electric circuit where the potential 
     *  difference is one volt and the current one ampere.</p>
     */
    public static final OntClass Watt = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Watt" );
    
    /** <p>It is the SI unit for radiative and other energy fluxes.</p> */
    public static final OntClass WattPerSquareMetre = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WattPerSquareMetre" );
    
    /** <p>Weather Forecasting, Meterology as an Internet of Things (IoT) applicative 
     *  domain.</p>
     */
    public static final OntClass Weather = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Weather" );
    
    /** <p>Luminosity.</p> */
    public static final OntClass WeatherLuminosity = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WeatherLuminosity" );
    
    /** <p>Weather Precipitation.</p> */
    public static final OntClass WeatherPrecipitation = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WeatherPrecipitation" );
    
    /** <p>A body's relative mass or the quantity of matter contained by it, giving rise 
     *  to a downward force; the heaviness of a person or thing.</p>
     */
    public static final OntClass Weight = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Weight" );
    
    /** <p>Device used to weight an object.</p> */
    public static final OntClass WeightSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WeightSensor" );
    
    /** <p>Measure the average power consumption of the WiFi interface nodes.</p> */
    public static final OntClass WiFiInterfaceEnergyMeter = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WiFiInterfaceEnergyMeter" );
    
    /** <p>The cooling effect of wind blowing on a surface.</p> */
    public static final OntClass WindChill = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WindChill" );
    
    /** <p>Device used to detect Wind Chill.</p> */
    public static final OntClass WindChillSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WindChillSensor" );
    
    /** <p>The geodetic azimuth of the direction from which the wind is blowing.</p> */
    public static final OntClass WindDirection = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WindDirection" );
    
    /** <p>Device used to detect wind direction.</p> */
    public static final OntClass WindDirectionSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WindDirectionSensor" );
    
    /** <p>The ratio of the distance covered by moving air to the time quantity taken 
     *  to cover it.</p>
     */
    public static final OntClass WindSpeed = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WindSpeed" );
    
    /** <p>Wind Speed Sensor, Anemometer or Wind Velocity Sensor is used to measure the 
     *  wind speed.</p>
     */
    public static final OntClass WindSpeedSensor = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WindSpeedSensor" );
    
    /** <p>An actuator to automatically open/close the window.</p> */
    public static final OntClass Window = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Window" );
    
    /** <p>Indicator of whether a person (or object) is working or not</p> */
    public static final OntClass WorkingState = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WorkingState" );
    
    /** <p>Indicator of whether the driver of a vehicle is present or not</p> */
    public static final OntClass WorkingStateDriver = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WorkingStateDriver" );
    
    /** <p>State of work of the first driver as defined in the FMS standard.</p> */
    public static final OntClass WorkingStateDriver1 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WorkingStateDriver1" );
    
    /** <p>State of work of the second driver as defined in the FMS standard.</p> */
    public static final OntClass WorkingStateDriver2 = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#WorkingStateDriver2" );
    
    /** <p>This unit is used to measure delta dew point within the Com4Innov tesbed. 
     *  Natural number (W/out unit).</p>
     */
    public static final OntClass Wout = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Wout" );
    
    /** <p>Year as a unit of time.</p> */
    public static final OntClass Year = m_model.createClass( "http://purl.org/iot/vocab/m3-lite#Year" );
    
}
